- id: appdaemon_heartbeat_checker
  alias: 'Appdaemon Heartbeat Checker'
  initial_state: 'on'
  condition:
    condition: template
    value_template: >
      {%- if states.sensor.appdaemon_heartbeat.last_changed -%}
        {{ (as_timestamp(now()) - as_timestamp(states.sensor.appdaemon_heartbeat.last_changed)) > 300 }}
      {%- else -%}
        true
      {%- endif -%}
  trigger:
    - platform: time_pattern
      minutes: '/5'
  action:
    - service: notify.group_notifications
      data:
        title: 'Alarm'
        message: "Appdaemon scheint nicht mehr zu funktionieren"